pipeline {
    agent any
    environment {
        DOCKER_REGISTRY = 'https://registry.octavia.ir'
        DOCKER_IMAGE = 'registry.octavia.ir/NAME'
        DOCKER_CONTAINER = 'NAME'
        PORT = 8585
    }
    stages {
        stage('Clone Repository') {
            steps {
                checkout scm
            }
        }
        stage('Build Docker Image') {
            steps {
                sh 'docker build -t $DOCKER_IMAGE .'
            }
        }
        stage('Push Docker Image') {
            steps {
                withDockerRegistry([credentialsId: 'nexus-credentials', url: DOCKER_REGISTRY]) {
                    sh 'docker push $DOCKER_IMAGE'
                }
            }
        }
        stage('Deploy Container') {
            steps {
                sh '''
                docker stop $DOCKER_CONTAINER || true
                docker rm $DOCKER_CONTAINER || true
                docker run -d --name $DOCKER_CONTAINER -p $PORT:$PORT $DOCKER_IMAGE
                '''
            }
        }
    }
}
